from PyQt5 import QtCore, QtGui, QtWidgets


class UiLightningPass(QtWidgets.QMainWindow):
    def setup_ui(self, lightning_pass):
        btn_font = "Segoe UI Light"
        lightning_pass.setObjectName("lightning_pass")
        lightning_pass.resize(800, 458)
        self.centralwidget = QtWidgets.QWidget(lightning_pass)
        self.centralwidget.setObjectName("centralwidget")
        self.welcome_label = QtWidgets.QLabel(self.centralwidget)
        self.welcome_label.setGeometry(QtCore.QRect(100, 70, 781, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.welcome_label.setFont(font)
        self.welcome_label.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.welcome_label.setObjectName("welcome_label")
        self.generate_password_btn = QtWidgets.QPushButton(self.centralwidget)
        self.generate_password_btn.setGeometry(QtCore.QRect(90, 210, 291, 111))
        font = QtGui.QFont()
        font.setFamily(btn_font)
        font.setPointSize(16)
        self.generate_password_btn.setFont(font)
        self.generate_password_btn.setObjectName("generate_password_btn")
        self.login_btn = QtWidgets.QPushButton(self.centralwidget)
        self.login_btn.setGeometry(QtCore.QRect(420, 210, 281, 51))
        font = QtGui.QFont()
        font.setFamily(btn_font)
        font.setPointSize(16)
        self.login_btn.setFont(font)
        self.login_btn.setObjectName("login_btn")
        self.register_button = QtWidgets.QPushButton(self.centralwidget)
        self.register_button.setGeometry(QtCore.QRect(420, 270, 281, 51))
        font = QtGui.QFont()
        font.setFamily(btn_font)
        font.setPointSize(16)
        self.register_button.setFont(font)
        self.register_button.setObjectName("register_button")
        lightning_pass.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(lightning_pass)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menulogin = QtWidgets.QMenu(self.menubar)
        self.menulogin.setObjectName("menulogin")
        self.menupassword = QtWidgets.QMenu(self.menubar)
        self.menupassword.setObjectName("menupassword")
        lightning_pass.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(lightning_pass)
        self.statusbar.setObjectName("statusbar")
        lightning_pass.setStatusBar(self.statusbar)
        self.actionlogin = QtWidgets.QAction(lightning_pass)
        self.actionlogin.setObjectName("actionlogin")
        self.actionregister = QtWidgets.QAction(lightning_pass)
        self.actionregister.setObjectName("actionregister")
        self.actiongenerate = QtWidgets.QAction(lightning_pass)
        self.actiongenerate.setObjectName("actiongenerate")
        self.menulogin.addAction(self.actionlogin)
        self.menulogin.addAction(self.actionregister)
        self.menupassword.addAction(self.actiongenerate)
        self.menubar.addAction(self.menupassword.menuAction())
        self.menubar.addAction(self.menulogin.menuAction())

        self.retranslate_ui(lightning_pass)
        QtCore.QMetaObject.connectSlotsByName(lightning_pass)

    def retranslate_ui(self, lightning_pass):
        _translate = QtCore.QCoreApplication.translate
        lightning_pass.setWindowTitle(_translate("lightning_pass", "MainWindow"))
        self.welcome_label.setText(_translate("lightning_pass", "Welcome to Lightning Pass!"))
        self.generate_password_btn.setText(_translate("lightning_pass", "Generate Password"))
        self.login_btn.setText(_translate("lightning_pass", "Login"))
        self.register_button.setText(_translate("lightning_pass", "Register"))
        self.menulogin.setTitle(_translate("lightning_pass", "users"))
        self.menupassword.setTitle(_translate("lightning_pass", "password"))
        self.actionlogin.setText(_translate("lightning_pass", "login"))
        self.actionregister.setText(_translate("lightning_pass", "register"))
        self.actiongenerate.setText(_translate("lightning_pass", "generate"))
