from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow


class Ui_LightningPass(QtWidgets.QMainWindow):
    def __init__(self, parent=None):
        super(Ui_LightningPass, self).__init__(parent)
        self.main_win = QMainWindow()
        self.setupUi(self.main_win)
        self.stackedWidget.setCurrentWidget(self.home)
        self.home_login_btn.clicked.connect(
            lambda: self.stackedWidget.setCurrentWidget(self.login)
        )
        self.home_register_btn.clicked.connect(
            lambda: self.stackedWidget.setCurrentWidget(self.register_2)
        )
        self.log_main_btn.clicked.connect(
            lambda: self.stackedWidget.setCurrentWidget(self.home)
        )

    def show(self):
        self.main_win.show()

    def setupUi(self, lightning_pass):
        lightning_pass.setObjectName("lightning_pass")
        lightning_pass.resize(1038, 592)
        self.centralwidget = QtWidgets.QWidget(lightning_pass)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 612, 213))
        self.stackedWidget.setObjectName("stackedWidget")
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.gridLayout = QtWidgets.QGridLayout(self.home)
        self.gridLayout.setObjectName("gridLayout")
        self.home_register_btn = QtWidgets.QPushButton(self.home)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(16)
        self.home_register_btn.setFont(font)
        self.home_register_btn.setObjectName("home_register_btn")
        self.gridLayout.addWidget(self.home_register_btn, 2, 1, 1, 1)
        self.home_login_btn = QtWidgets.QPushButton(self.home)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(16)
        self.home_login_btn.setFont(font)
        self.home_login_btn.setObjectName("home_login_btn")
        self.gridLayout.addWidget(self.home_login_btn, 1, 1, 1, 1)
        self.home_welcome_lbl = QtWidgets.QLabel(self.home)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.home_welcome_lbl.setFont(font)
        self.home_welcome_lbl.setLocale(
            QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates)
        )
        self.home_welcome_lbl.setObjectName("home_welcome_lbl")
        self.gridLayout.addWidget(self.home_welcome_lbl, 0, 0, 1, 2)
        self.home_generate_password_btn = QtWidgets.QPushButton(self.home)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(16)
        self.home_generate_password_btn.setFont(font)
        self.home_generate_password_btn.setObjectName("home_generate_password_btn")
        self.gridLayout.addWidget(self.home_generate_password_btn, 1, 0, 2, 1)
        self.stackedWidget.addWidget(self.home)
        self.login = QtWidgets.QWidget()
        self.login.setObjectName("login")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.login)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.log_login_lbl = QtWidgets.QLabel(self.login)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(26)
        self.log_login_lbl.setFont(font)
        self.log_login_lbl.setObjectName("log_login_lbl")
        self.gridLayout_2.addWidget(self.log_login_lbl, 0, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.login)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 1, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.login)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 2, 0, 1, 1)
        self.log_login_btn_2 = QtWidgets.QPushButton(self.login)
        self.log_login_btn_2.setObjectName("log_login_btn_2")
        self.gridLayout_2.addWidget(self.log_login_btn_2, 3, 0, 1, 1)
        self.log_forgot_pass_btn = QtWidgets.QPushButton(self.login)
        self.log_forgot_pass_btn.setObjectName("log_forgot_pass_btn")
        self.gridLayout_2.addWidget(self.log_forgot_pass_btn, 3, 1, 1, 1)
        self.log_main_btn = QtWidgets.QPushButton(self.login)
        self.log_main_btn.setObjectName("log_main_btn")
        self.gridLayout_2.addWidget(self.log_main_btn, 3, 2, 1, 1)
        self.log_progress_bar = QtWidgets.QProgressBar(self.login)
        self.log_progress_bar.setProperty("value", 24)
        self.log_progress_bar.setObjectName("log_progress_bar")
        self.gridLayout_2.addWidget(self.log_progress_bar, 4, 0, 1, 3)
        self.stackedWidget.addWidget(self.login)
        self.register_2 = QtWidgets.QWidget()
        self.register_2.setObjectName("register_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.register_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.reg_register_lbl = QtWidgets.QLabel(self.register_2)
        self.reg_register_lbl.setObjectName("reg_register_lbl")
        self.gridLayout_3.addWidget(self.reg_register_lbl, 0, 0, 1, 2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.register_2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_3.addWidget(self.lineEdit_3, 1, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.register_2)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_3.addWidget(self.lineEdit_4, 2, 0, 1, 1)
        self.reg_register_btn = QtWidgets.QPushButton(self.register_2)
        self.reg_register_btn.setObjectName("reg_register_btn")
        self.gridLayout_3.addWidget(self.reg_register_btn, 3, 0, 1, 1)
        self.reg_login_btn = QtWidgets.QPushButton(self.register_2)
        self.reg_login_btn.setObjectName("reg_login_btn")
        self.gridLayout_3.addWidget(self.reg_login_btn, 3, 1, 1, 1)
        self.reg_main_btn = QtWidgets.QPushButton(self.register_2)
        self.reg_main_btn.setObjectName("reg_main_btn")
        self.gridLayout_3.addWidget(self.reg_main_btn, 3, 2, 1, 1)
        self.stackedWidget.addWidget(self.register_2)
        lightning_pass.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(lightning_pass)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1038, 26))
        self.menubar.setObjectName("menubar")
        self.menulogin = QtWidgets.QMenu(self.menubar)
        self.menulogin.setObjectName("menulogin")
        self.menupassword = QtWidgets.QMenu(self.menubar)
        self.menupassword.setObjectName("menupassword")
        lightning_pass.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(lightning_pass)
        self.statusbar.setObjectName("statusbar")
        lightning_pass.setStatusBar(self.statusbar)
        self.actionlogin = QtWidgets.QAction(lightning_pass)
        self.actionlogin.setObjectName("actionlogin")
        self.actionregister = QtWidgets.QAction(lightning_pass)
        self.actionregister.setObjectName("actionregister")
        self.actiongenerate = QtWidgets.QAction(lightning_pass)
        self.actiongenerate.setObjectName("actiongenerate")
        self.menulogin.addAction(self.actionlogin)
        self.menulogin.addAction(self.actionregister)
        self.menupassword.addAction(self.actiongenerate)
        self.menubar.addAction(self.menupassword.menuAction())
        self.menubar.addAction(self.menulogin.menuAction())

        self.retranslateUi(lightning_pass)

    def retranslateUi(self, lightning_pass):
        _translate = QtCore.QCoreApplication.translate
        lightning_pass.setWindowTitle(_translate("lightning_pass", "MainWindow"))
        self.home_register_btn.setText(_translate("lightning_pass", "Register"))
        self.home_login_btn.setText(_translate("lightning_pass", "Login"))
        self.home_welcome_lbl.setText(
            _translate("lightning_pass", "Welcome to Lightning Pass!")
        )
        self.home_generate_password_btn.setText(
            _translate("lightning_pass", "Generate Password")
        )
        self.log_login_lbl.setText(_translate("lightning_pass", "Login"))
        self.lineEdit_2.setText(_translate("lightning_pass", "Username"))
        self.lineEdit.setText(_translate("lightning_pass", "Password"))
        self.log_login_btn_2.setText(_translate("lightning_pass", "Login"))
        self.log_forgot_pass_btn.setText(
            _translate("lightning_pass", "Forgot Password?")
        )
        self.log_main_btn.setText(_translate("lightning_pass", "Main Menu"))
        self.reg_register_lbl.setText(_translate("lightning_pass", "Register"))
        self.lineEdit_3.setText(_translate("lightning_pass", "username"))
        self.lineEdit_4.setText(_translate("lightning_pass", "password"))
        self.reg_register_btn.setText(_translate("lightning_pass", "Register"))
        self.reg_login_btn.setText(_translate("lightning_pass", "Login"))
        self.reg_main_btn.setText(_translate("lightning_pass", "Main Menu"))
        self.menulogin.setTitle(_translate("lightning_pass", "users"))
        self.menupassword.setTitle(_translate("lightning_pass", "password"))
        self.actionlogin.setText(_translate("lightning_pass", "login"))
        self.actionregister.setText(_translate("lightning_pass", "register"))
        self.actiongenerate.setText(_translate("lightning_pass", "generate"))
