# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LightningPass(object):
    def setupUi(self, LightningPass):
        LightningPass.setObjectName("LightningPass")
        LightningPass.resize(800, 458)
        self.centralwidget = QtWidgets.QWidget(LightningPass)
        self.centralwidget.setObjectName("centralwidget")
        self.WelcomeLabel = QtWidgets.QLabel(self.centralwidget)
        self.WelcomeLabel.setGeometry(QtCore.QRect(100, 70, 781, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.WelcomeLabel.setFont(font)
        self.WelcomeLabel.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.WelcomeLabel.setObjectName("WelcomeLabel")
        self.GeneratePasswordBtn = QtWidgets.QPushButton(self.centralwidget)
        self.GeneratePasswordBtn.setGeometry(QtCore.QRect(90, 210, 291, 111))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(16)
        self.GeneratePasswordBtn.setFont(font)
        self.GeneratePasswordBtn.setObjectName("GeneratePasswordBtn")
        self.LoginBtn = QtWidgets.QPushButton(self.centralwidget)
        self.LoginBtn.setGeometry(QtCore.QRect(420, 210, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(16)
        self.LoginBtn.setFont(font)
        self.LoginBtn.setObjectName("LoginBtn")
        self.RegisterBtn = QtWidgets.QPushButton(self.centralwidget)
        self.RegisterBtn.setGeometry(QtCore.QRect(420, 270, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(16)
        self.RegisterBtn.setFont(font)
        self.RegisterBtn.setObjectName("RegisterBtn")
        LightningPass.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LightningPass)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menulogin = QtWidgets.QMenu(self.menubar)
        self.menulogin.setObjectName("menulogin")
        self.menupassword = QtWidgets.QMenu(self.menubar)
        self.menupassword.setObjectName("menupassword")
        LightningPass.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LightningPass)
        self.statusbar.setObjectName("statusbar")
        LightningPass.setStatusBar(self.statusbar)
        self.actionlogin = QtWidgets.QAction(LightningPass)
        self.actionlogin.setObjectName("actionlogin")
        self.actionregister = QtWidgets.QAction(LightningPass)
        self.actionregister.setObjectName("actionregister")
        self.actiongenerate = QtWidgets.QAction(LightningPass)
        self.actiongenerate.setObjectName("actiongenerate")
        self.menulogin.addAction(self.actionlogin)
        self.menulogin.addAction(self.actionregister)
        self.menupassword.addAction(self.actiongenerate)
        self.menubar.addAction(self.menupassword.menuAction())
        self.menubar.addAction(self.menulogin.menuAction())

        self.retranslateUi(LightningPass)
        QtCore.QMetaObject.connectSlotsByName(LightningPass)

    def retranslateUi(self, LightningPass):
        _translate = QtCore.QCoreApplication.translate
        LightningPass.setWindowTitle(_translate("LightningPass", "MainWindow"))
        self.WelcomeLabel.setText(_translate("LightningPass", "Welcome to Lightning Pass!"))
        self.GeneratePasswordBtn.setText(_translate("LightningPass", "Generate Password"))
        self.LoginBtn.setText(_translate("LightningPass", "Login"))
        self.RegisterBtn.setText(_translate("LightningPass", "Register"))
        self.menulogin.setTitle(_translate("LightningPass", "users"))
        self.menupassword.setTitle(_translate("LightningPass", "password"))
        self.actionlogin.setText(_translate("LightningPass", "login"))
        self.actionregister.setText(_translate("LightningPass", "register"))
        self.actiongenerate.setText(_translate("LightningPass", "generate"))
