# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lightning_pass/gui/static/qt_designer/splash_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loading_widget(object):
    def setupUi(self, loading_widget):
        loading_widget.setObjectName("loading_widget")
        loading_widget.resize(410, 143)
        self.gridLayout = QtWidgets.QGridLayout(loading_widget)
        self.gridLayout.setObjectName("gridLayout")
        self.loading_label = QtWidgets.QLabel(loading_widget)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(16)
        self.loading_label.setFont(font)
        self.loading_label.setObjectName("loading_label")
        self.gridLayout.addWidget(self.loading_label, 0, 0, 1, 1)
        self.loading_progress_bar = QtWidgets.QProgressBar(loading_widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(10)
        self.loading_progress_bar.setFont(font)
        self.loading_progress_bar.setMaximum(100)
        self.loading_progress_bar.setProperty("value", 0)
        self.loading_progress_bar.setObjectName("loading_progress_bar")
        self.gridLayout.addWidget(self.loading_progress_bar, 1, 0, 1, 1)

        self.retranslateUi(loading_widget)
        QtCore.QMetaObject.connectSlotsByName(loading_widget)

    def retranslateUi(self, loading_widget):
        _translate = QtCore.QCoreApplication.translate
        loading_widget.setWindowTitle(_translate("loading_widget", "Form"))
        self.loading_label.setText(
            _translate("loading_widget", "Loading Lightning Pass..."),
        )
