from passgen import passgen


class Generator:
    """The Generator class holds user's chosen parameters for password generation
    and contains the password generation functionality."""

    def __init__(
        self,
        randomness_lst,
        length,
        numbers,
        symbols,
        lowercase,
        uppercase,
    ):
        """Class contructor."""
        self.val_lst = randomness_lst
        self.length = length
        self.numbers = numbers
        self.symbols = symbols
        self.lowercase = lowercase
        self.uppercase = uppercase

    def __repr__(self):
        """Provide information about this class."""
        return f"""Generator(
               {self.val_lst},
               {self.length},
               {self.numbers},
               {self.symbols},
               {self.lowercase},
               {self.uppercase})"""

    def generate_password(self):
        """Generate a password by passgen library.
        Password generation is based on the chosen parameters in the GUI.

        :returns password: password generated by passgen
        :rtype str

        """
        if self.lowercase and self.uppercase:
            case_type = "both"
        elif self.lowercase is False:
            case_type = "upper"
        elif self.uppercase is False:
            case_type = "lower"

        password = passgen(
            length=self.length,
            punctuation=self.symbols,
            digits=self.numbers,
            case=case_type,
        )
        return password
